services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=tracking-service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=Supervisor'
    ports:
      - '5432:5432'
