server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/v1/trips/oneway-trip/**
          filters:
            - RewritePath=/api/v1/trips/oneway-trip/(?<remaining>.*), /$\{remaining}
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/v1/trips/round-trip/**
          filters:
            - RewritePath=/api/v1/trips/round-trip/(?<remaining>.*), /$\{remaining}
