spring:
  application:
    name: gateway-service

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

gateway:
  discovery:
    locator:
      enabled: true
  routes:
    - id: reservation-service
      uri: lb://reservation-service
      predicates:
        - Path=/api/v1/reservations/**
