server:
  port: 8081
spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  application:
    name: tracking-service
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
